blog/urls.py
from django.urls import path
from .import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name = 'home'),
    path('about/', views.about, name='about'),
    path('add-post/', views.AddPost.as_view(), name= 'addPost'),
    path('post-detail/<str:pk>/', views.PostDetail.as_view(), name="postDetail"),
    path('all-posts/', views.PostList.as_view(), name='allPosts'),
    path('add-comment/',views.addComment, name="addComment"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blog.urls")),
    path('accounts/', include('allauth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from django.urls import reverse
from gdstorage.storage import GoogleDriveStorage


gd_storage = GoogleDriveStorage()


class Post(models.Model):
    title = models.CharField(max_length = 250)
    thumbnail = models.ImageField(upload_to = 'images/', null = True, blank = True,storage=gd_storage)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = RichTextField(blank = True, null= True)
    category = models.CharField(max_length=250,blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:postDetail", kwargs={"pk": self.pk})
    


class Comment(models.Model):
    text = models.CharField(max_length=300)
    author = models.ForeignKey(User, on_delete = models.CASCADE)
    related_post = models.ForeignKey(Post, on_delete=models.CASCADE)
    timestamp =  models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from ckeditor.fields import RichTextField
from django.db.models import fields

from .models import Comment, Post

class PostForm(forms.ModelForm):
    title = forms.CharField(max_length=300, widget=forms.TextInput(attrs={ 'class':'form-control', 'placeholder':"Title"}))
    category = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Category'}))
    class Meta:
        model = Post
        fields = ['title', 'thumbnail','content','category',]

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text', 'author','related_post']

blog/views.py
from django.shortcuts import redirect, render
from django.views.generic import CreateView, DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.contrib.auth.models import User
import json
from .models import Post, Comment
from .forms import PostForm,CommentForm


def index(request):
    recent_posts = Post.objects.all().order_by("-timestamp")[0:3]
    top_posts = Post.objects.all()[0:3]
    contex = {'recent_posts':recent_posts, "top_posts":top_posts}
    return render(request, 'blog/index.html', contex)

def addComment(request):
    comment_dict = json.load(request)
    author = User.objects.get(id = comment_dict['author'])
    post = Post.objects.get(id = comment_dict['related_post'])
    comment = Comment(author=author, text=comment_dict['text'],related_post=post)
    comment.save()
    return JsonResponse({"text":comment_dict['text'], 'author':author.username})


def about(request):
    return render(request, 'blog/about.html')

class AddPost(LoginRequiredMixin,CreateView):
    login_url = '/accounts/login/'
    model = Post
    form_class = PostForm
    # success_url = reverse_lazy('blog:home') #specify success_url or define get_absolute_url method in model

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
class PostDetail(DetailView):
    model = Post
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        comments = Comment.objects.all().filter(related_post = kwargs['object'].id)
        context = super().get_context_data(**kwargs)
        context['comments'] = comments
        return context

class PostList(ListView):
    model = Post
    context_object_name = 'posts'
    ordering = "timestamp"
    paginate_by = 5

blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block title%}About Us {% endblock %}

{% block content %}

    <header class="py-5">
    <div class="container px-5">
        <div class="row justify-content-center">
            <div class="col-lg-8 col-xxl-6">
                <div class="text-center my-5">
                    <h1 class="fw-bolder mb-3">This blog is to learn new things.</h1>
                    <p class="lead fw-normal text-muted mb-4">Started this website as personel project to mantain record what I learnt till yet. If you find this is usefull share with others.</p>
                    <h3class="text-right">~Akash B Bhagat</h3>
                </div>
            </div>
        </div>

        <div class="container">
            <aside class="bg-primary bg-gradient rounded-3 p-3 p-sm-5 mt-2">
                <div class="d-flex align-items-center justify-content-between flex-column flex-xl-row text-center text-xl-start">
                    <div class="mb-4 mb-xl-0">
                        <div class="fs-3 fw-bold text-white"> You can put your feedback at  
                            <div class="text-white-60">ba441380@gmail.com</div>
                        </div>
                    </div>
                    <div class="ms-xl-4">
                        <div class="fs-5 fw-bold text-white"> Get in touch.
                        </div>
                        <div class="input-group mb-2">
                            <input class="form-control" type="text" placeholder="Email address..." aria-label="Email address..." aria-describedby="button-newsletter">
                                &nbsp;<button class="btn btn-outline-dark" id="button-newsletter" type="button"><strong>Remind me</strong></button>
                        </div>
                        <div class="small text-white-50">We care about privacy, and will never share your data.</div>
                    </div>
                </div>
            </aside>
        </div>
    </div>
</header>

{% endblock %}

blog/templates/blog/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>{% block title%} {% endblock %}</title>
  </head>

  <body>
    {% include 'blog/navbar.html' %}
    {% block content %}

    {% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    -->
  </body>
</html>

blog/templates/blog/header_crousel.html
<div class="my-1">

  <div
    id="carouselExampleIndicators"
    class="carousel slide"
    data-bs-ride="carousel"
  >
    <div class="carousel-indicators">
    {% for i in recent_posts%}
      <button type="button" data-bs-target="#carouselExampleIndicators" 
      data-bs-slide-to={{ forloop.counter0 }} 
      class="active"
        {% if forloop.counter == 1 %}
          aria-current="true"
        {% endif %}
        aria-label="Slide {{ forloop.counter }}"
      ></button>
      {% endfor %}

    </div>
    <div class="carousel-inner">
    {% for post in recent_posts%}
      <div class="carousel-item {% if forloop.counter == 1 %} active {% endif %}" style="background:#2E86B1;">
              <div class="row">
                <div class="col">
                  <header class="bg-transperant py-1">
                    <div class="container px-5">
                      <div class="row gx-5 align-items-center justify-content-center">
                        <div class="col-lg-8 col-xl-7 col-xxl-6">
                          <div class="m-5 text-center text-xl-start">
                            <h3 class="display-6 fw-bolder text-white mb-2">
                              {{post.title}}
                            </h3>
                            <p class="lead text-light mb-4">
                              {{post.author}}
                            </p>
                            <div class="d-grid gap-3 d-sm-flex justify-content-sm-center justify-content-xl-start">
                              <a class="btn btn-primary btn-lg px-4 me-sm-3" href="{% url 'blog:postDetail' post.id %}">Read Now</a>
                            </div>
                          </div>
                        </div>
                        <div class="col-xl-5 col-xxl-6 d-none d-xl-block text-center">
                          <img
                            class="img-fluid rounded-3 my-4"
                            {% comment %} src="https://dummyimage.com/600x400/343a40/6c757d" {% endcomment %}
                            src="{{post.thumbnail.url}}"
                            alt="..."
                          />
                        </div>
                      </div>
                    </div>
                  </header>
                </div>
              </div>
        </div>

    {% endfor %}

    </div>
    <button
      class="carousel-control-prev"
      type="button"
      data-bs-target="#carouselExampleIndicators"
      data-bs-slide="prev"
    >
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button
      class="carousel-control-next"
      type="button"
      data-bs-target="#carouselExampleIndicators"
      data-bs-slide="next"
    >
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block title%} Home {% endblock %}

{% block content %}
    {% include 'blog/header_crousel.html' %}

    {% include 'blog/top_posts.html' %}
{% endblock %}

blog/templates/blog/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-warning sticky-top">
    <div class="container px-5">
        <a class="navbar-brand" href="{% url 'blog:home' %}"><strong>Postee</strong></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link" href="{% url 'blog:home' %}">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'blog:about' %}">About</a></li>
                <li class="nav-item dropdown">
                {% if user.is_authenticated %}
                    <a class="nav-link dropdown-toggle" id="navbarDropdownBlog" href="#" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">{{request.user}}</a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownBlog">
                        <li><a class="dropdown-item" href="{% url 'blog:addPost' %}">Add Post</a></li>
                        <li><a class="dropdown-item" href="{% url 'account_logout' %}">Log Out</a></li>
                    </ul>
                {% else %}
                     <li class="nav-item"><a class="nav-link" href="{% url 'account_login' %}">Sign In</a></li>
                {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>
{% comment %} 
<nav class="site-header sticky-top py-1" style="background: #83a4d4;  /* fallback for old browsers */
background: -webkit-linear-gradient(to right, #b6fbff, #83a4d4);  /* Chrome 10-25, Safari 5.1-6 */
background: linear-gradient(to right, #b6fbff, #83a4d4); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
">
      <div class="container d-flex flex-column flex-md-row justify-content-between">
        <a class="py-2" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="d-block mx-auto"><circle cx="12" cy="12" r="10"></circle><line x1="14.31" y1="8" x2="20.05" y2="17.94"></line><line x1="9.69" y1="8" x2="21.17" y2="8"></line><line x1="7.38" y1="12" x2="13.12" y2="2.06"></line><line x1="9.69" y1="16" x2="3.95" y2="6.06"></line><line x1="14.31" y1="16" x2="2.83" y2="16"></line><line x1="16.62" y1="12" x2="10.88" y2="21.94"></line></svg>
        </a>
        <a class="py-2 d-none d-md-inline-block" href="#">Tour</a>
        <a class="py-2 d-none d-md-inline-block" href="#">Product</a>
        <a class="py-2 d-none d-md-inline-block" href="#">Features</a>
        <a class="py-2 d-none d-md-inline-block" href="#">Enterprise</a>
        <a class="py-2 d-none d-md-inline-block" href="#">Support</a>
        <a class="py-2 d-none d-md-inline-block" href="#">Pricing</a>
        <a class="py-2 d-none d-md-inline-block" href="#">Cart</a>
      </div>
    </nav> {% endcomment %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %} 

{% block title %} Post {% endblock %}
   
{% block content %}
    <section class="py-0">
        <div class="container px-1 my-2">
            <div class="row gx-3">
                <div class="col-lg-2">
                    <div class="d-flex align-items-center mt-lg-5 mb-4">
                        <img class="img-fluid rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." />
                        <div class="ms-3">
                            <div class="fw-bold">{{post.author}}</div>
                            <div class="text-muted">....</div>
                        </div>
                    </div>
                </div>

                
                <div class="col-lg-10 rounded" style = "background:#70BAB3;">
                    <!-- Post content-->
                    <article class="p-3 rounded">
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <h1 class="fw-bolder mb-1">{{post.title}}</h1>
                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2">{{post.timestamp}}</div>
                            <!-- Post categories-->
                            <a class="badge bg-primary bg-gradient text-decoration-none link-light" href="">{{post.category}}</a>
                        </header>
                        <!-- Post content-->
                        <div class="container rounded p-2">
                            {{ post.content|safe }}
                        
                        </div>
                        <section class="mb-5">
                        
                        </section>
                    </article>
                </div>
                    <!-- Comments section-->
                <div class="row border-top border-info my-3">
                    <div class="col-3"></div>
                    <div class="col-9 w-70 h-50">
                        {% if user.is_authenticated %}
                            <section>
                                <h4>Let us know your feedback, comment here.</h4>
                                <div class="card my-2" style="background:#B2DFDB">
                                    <div class="card-body">
                                        <!-- Comment form-->
                                        <form id="commentForm" class="mb-4 text-center" method="POST">
                                            {% csrf_token %}
                                            <input type="number" name="author" value={{ post.author.id }} hidden>
                                            <input type="number" name="relatedPost" value={{ post.id }} hidden>
                                            <textarea class="form-control" rows="3" name="commentText" placeholder="Join the discussion and leave a comment!"></textarea>
                                            <button id = "addComment" class="btn btn-outline-success mt-1" onclick="addComment"><strong>Add comment</strong></button>
                                        </form>

                                        <!-- Single comment-->
                                        <div id="comments">
                                            {% for comment in comments %}
                                                <div class="d-flex py-2">
                                                    <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                                    <div class="ms-3">
                                                        <div class="fw-bold">{{comment.author}}</div>
                                                        {{ comment.text }}
                                                    </div>
                                                </div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            </section>
                        {% else %}
                            <div class="p-2 m-1 bg-info rounded text-center">
                                <h3> To write your comment <a href="{% url 'account_login' %}?next={% url 'blog:postDetail' post.id %}" class="text-decoration-none" >log In </a>First.
                                </h3>
                            </div>
                        {% endif %}
                    </div>
                </div>    

            </div>
        </div>
    </section>
{% endblock %}

{% block script%} 
    {% comment %} let btn = document.querySelector("#addComment");
    btn.addEventListener('click',addComment) {% endcomment %}
    let form = document.querySelector("#commentForm");
    form.addEventListener('submit',addComment)
    
    function addComment(e){
        e.preventDefault();
   
        let formdata = new FormData(form);
        let data = {
            "author":formdata.get("author"),
            "related_post":formdata.get("relatedPost"),
            "text":formdata.get("commentText"),
        }


fetch("https://postee347.herokuapp.com/add-comment/", {
      method: 'POST',
      credentials: 'same-origin',
      headers:{
          'Accept': 'application/json',
          'X-Requested-With': 'XMLHttpRequest', //Necessary to work with request.is_ajax()
          'X-CSRFToken': formdata.get("csrfmiddlewaretoken").toString(),
  },
      body: JSON.stringify(data) //JavaScript object of data to POST
  })
  .then(response => {
        return response.json(); //Convert response to JSON
  })
  .then(data => {
      

  let cmt = ` <div class="d-flex py-2">
                        <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                        <div class="ms-3">
                            <div class="fw-bold">${data["author"]}</div>
                            ${data["text"]}
                        </div>
                    </div>
                    `
    document.querySelector("#comments").innerHTML += cmt;
  })

    
        form.reset();

    }
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %} 
{% block title %} Add Post {% endblock %} {% block content %}
<div class="continer mt-2">
  <h3 class="text-center">Write your post here.</h3>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %} {{ form.media }}
    <div class="row">
      <div class="col-2"></div>
      <div class="col-8">
              <div class="row mt-1">
          {{ form.author}}
        </div>
        <div class="row mt-1">
          {{ form.title}}
        </div>
        <div class="row mt-1">
          {{ form.category}}
        </div>
        <div class="row mt-2">
          <div class="col-4">
            {{ form.thumbnail.label }} 
            {{ form.thumbnail}}
          </div>
          <div class="col-8"></div>
        </div>
        <div class="row mt-2">
            {{ form.content.label }} {{form.content}}
        </div>
        <div class="text-center mt-2">
          <button type="submit" class="btn btn-outline-info">
            <strong>Add Post </strong>
          </button>
        </div>
      </div>
      <div class="col-2"></div>
    </div>
  </form>
</div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block title%} All Posts {% endblock %}

{% block content %}

    <div class="container">
        {% for post in posts %}
            
            <section class="py-1 my-5 shadow rounded">
                    <div class="container px-2 my-1">
                        <div class="row gx-1 align-items-center">
                            <div class="col-lg-6 {% if forloop.counter|divisibleby:2 == 0 %} order-first order-lg-last {% endif %}">
                                <a class="text-decoration-none" href="{% url 'blog:postDetail' post.id %}"> 
                                    <img class="img-fluid rounded mb-5 mb-lg-0" src="{{ post.thumbnail.url }}" alt="...">
                                </a>
                            </div>
                            <div class="col-lg-6">
                                <div class="h2 fw-bolder">{{ post.title }}</div>
                                <div class="badge bg-primary bg-gradient rounded-pill mb-2">{{post.category}}</div>
                                <p class="lead fw-normal text-muted mb-0">{{ post.content|striptags|slice:150}}...</p>
                            
                                <a class="text-decoration-none" href="{% url 'blog:postDetail' post.id %}">
                                    Read more
                                    <i class="bi bi-arrow-right">>>></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </section>

        {% endfor %}
        
        <div class="container text-center">
            {% if is_paginated %} 

            {% if page_obj.has_previous %}
                <a href="?page=1" class="btn btn-outline-info mb-4">First</a>
                <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-info mb-4">Previous</a>
            {% endif %} 


            {% for num in page_obj.paginator.page_range %} 
                
                {% if page_obj.number == num%}
                <a href="?page={{ num }}" class="btn btn-info mb-4">{{ num }}</a>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3'%}
                <a href="?page={{ num }}" class="btn btn-outline-info mb-4">{{ num }}</a>
                {% endif %} 

            {% endfor %} 



            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number}}" class="btn btn-outline-info mb-4" >Next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-outline-info mb-4" >last</a>
            {% endif %} 
            {% endif %}
        </div>
</div>
{% endblock %}

blog/templates/blog/top_posts.html
<section >
        <div class="container px-5 my-5">
            <div class="row gx-5 justify-content-center">
                <div class="col-lg-8 col-xl-6">
                    <div class="text-center">
                        <h2 class="fw-bolder">From our blog</h2>
                        <p class="lead fw-normal text-muted mb-5">This blog is started recently, You can find posts related to Programming for now. If have any issue contact us. 
                </div>
            </div>
            
    {% if  top_posts%}
            <div class="row gx-4 shadow rounded" style="background-color : #AED6F1;">
            <h2 class="fw-bolder fs-4 mt-2 text-center">Top Stories</h2>
            <div class="text-end mb-xl-2">
                {% if user.is_authenticated %}
                    <a class="text-decoration-none btn btn-outline-info fw-bold m-2" href="{% url 'blog:addPost' %}">
                        Add new Post
                        <i class="bi bi-arrow-right"></i>
                    </a>
                {% endif %}
                <a class="text-decoration-none btn btn-outline-secondary fw-bold m-2" href="{% url 'blog:allPosts' %}">
                    More Posts
                    <i class="bi bi-arrow-right">>>></i>
                </a>
            </div>

            {% for post in top_posts%}
                <div class="col-lg-4 my-4">
                    <div class="card h-100 shadow border-0">
                        <img class="card-img-top" src="{{ post.thumbnail.url }}" alt="...">
                        <div class="card-body p-4">
                            <div class="badge bg-primary bg-gradient rounded-pill mb-2">{{post.category}}</div>
                            <a class="text-decoration-none link-dark stretched-link" href="{% url 'blog:postDetail' post.id %}"><h5 class="card-title mb-3">{{ post.title }}</h5></a>
                        </div>
                        <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                            <div class="d-flex align-items-end justify-content-between">
                                <div class="d-flex align-items-center">
                                    <img class="rounded-circle me-3" src="https://dummyimage.com/40x40/ced4da/6c757d" alt="...">
                                    <div class="small">
                                        <div class="fw-bold">{{post.author}}</div>
                                        <div class="text-muted">{{post.timestamp|date:"d M Y"}}</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}



            </div>
    {% endif %}

            <!-- Call to action-->

        </div>
</section>